import {
  FiGrid,
  FiTruck,
  FiMap,
  FiCalendar,
  FiClipboard,
  FiTag,
  FiCreditCard,
  FiNavigation,
  FiBarChart2,
  FiUsers,
  FiSettings,
  FiCompass,
  FiUser,
  FiSearch,
  FiBookOpen,
  FiCamera,
  FiList,
  FiFileText,
  FiHelpCircle,
  FiMessageCircle,
  FiActivity,
  FiStar,
} from 'react-icons/fi';
import { ROLES } from '../utils/constants';

export const NAV_CONFIG = {
  [ROLES.ADMIN]: [
    { label: 'Dashboard', to: '/admin/dashboard', icon: FiGrid },
    { label: 'Buses', to: '/admin/buses', icon: FiTruck },
    { label: 'Routes', to: '/admin/routes', icon: FiMap },
    { label: 'Schedules', to: '/admin/schedules', icon: FiCalendar },
    { label: 'Bookings', to: '/admin/bookings', icon: FiClipboard },
    { label: 'Tickets', to: '/admin/tickets', icon: FiTag },
    { label: 'Payments', to: '/admin/payments', icon: FiCreditCard },
    { label: 'Live Tracking', to: '/admin/tracking', icon: FiNavigation },
    { label: 'Reports & Analytics', to: '/admin/reports', icon: FiBarChart2 },
    { label: 'Staff Reports', to: '/admin/staff-reports', icon: FiFileText },
    { label: 'Support Overview', to: '/admin/support', icon: FiActivity },
    { label: 'Reviews Overview', to: '/admin/reviews', icon: FiStar },
    { label: 'Users', to: '/admin/users', icon: FiUsers },
    { label: 'Settings', to: '/admin/settings', icon: FiSettings },
  ],
  [ROLES.STAFF]: [
    { label: 'Dashboard', to: '/staff/dashboard', icon: FiGrid },
    { label: 'Bookings', to: '/staff/bookings', icon: FiClipboard },
    { label: 'Ticketing', to: '/staff/tickets', icon: FiTag },
    { label: 'Scan Ticket', to: '/staff/scan-ticket', icon: FiCamera },
    { label: 'Boarding History', to: '/staff/boarding-history', icon: FiList },
    { label: 'Payments', to: '/staff/payments', icon: FiCreditCard },
    { label: 'Schedules', to: '/staff/schedules', icon: FiCalendar },
    { label: 'Reports', to: '/staff/reports', icon: FiFileText },
    { label: 'Support Management', to: '/staff/support', icon: FiMessageCircle },
  ],
  [ROLES.DRIVER]: [
    { label: 'Dashboard', to: '/driver/dashboard', icon: FiGrid },
    { label: 'Trip Console', to: '/driver/trip', icon: FiNavigation },
    { label: 'My Schedule', to: '/driver/schedule', icon: FiCalendar },
    { label: 'Profile', to: '/driver/profile', icon: FiUser },
  ],
  [ROLES.CUSTOMER]: [
    { label: 'Search Trips', to: '/customer/home', icon: FiSearch },
    { label: 'My Bookings', to: '/customer/bookings', icon: FiBookOpen },
    { label: 'My Tickets', to: '/customer/tickets', icon: FiTag },
    { label: 'Track My Bus', to: '/customer/track', icon: FiCompass },
    { label: 'Support', to: '/customer/support', icon: FiHelpCircle },
    { label: 'Profile', to: '/customer/profile', icon: FiUser },
  ],
};
